### ISSUE TITLE
[BUG] Error when opening session with Gitlab

### ISSUE THREAD

**Issue by kenkeiras** [stroveio/strove.io#325]
**Describe the bug**

When trying to log in https://strove.io/ with GitLab, after introducing user and password on the GitLab platform get an error: `The redirect URI included is not valid`.

**Expected behavior**

The Strove dashboard should open with the associated GitLab user.

**To Reproduce**

1. Go to 'https://strove.io/ (with no previous login)
2. Click on 'Login'
3. Click on 'Gitlab'
4. Introduce gitlab user and password if asked for it
5. See error

**Screenshots**

![sshot](https://user-images.githubusercontent.com/354122/76400098-0fc8c100-6380-11ea-9ab8-5e2e92441d5c.png)

**Please complete the following information:**
 - OS: Debian Linux
 - Browser Firefox
 - Version 68.5 (esr)

**Comment by AdamZaczek** [comment]
Good catch, thanks!
