### ISSUE TITLE
Dashboard option not showing in nav

### ISSUE THREAD

**Issue by moT01** [stroveio/strove.io#363]
First of all, very cool project everyone 👍 

I've been testing it out and found some bugs I think, let me know if I'm in the wrong spot or not filing these properly or something.

The `dashboard` option doesn't show up in the nav when you **first** load a project from an embed snippet...

![Screen Shot 2020-04-14 at 9 55 10 AM](https://user-images.githubusercontent.com/20648924/79241016-17283200-7e38-11ea-87c7-e88bf91e132b.png)

If I reload the project, the option shows up. This only happens when using the embed option, and only on the first time loading it. It does not happen when you add a project from your dashboard.

Tested on:
High Sierra 10.13.6
Firefox 75.0 & Chrome 80.0.3987.163

**Comment by AdamZaczek** [comment]
Thanks!
We do not have an embed version documented fully for now. It's customized to be used for one project at a time, inside another website.

Right now the dashboard is disabled in embed by default.

Do you guys need it enabled? If you need it for testing and not live, one way to do it is to access it like:
```
https://strove.io/embed/editor/?repoUrl=https://github.com/stroveio/strove.io
```

By the way, I just checked your organization! Let me know if you need unlimited access, it might be useful for testing stuff!

**Comment by moT01** [comment]
Thanks, I'm not sure what we need at the moment, I'm just sharing some things I found for now.

This particular issue just seems inconsistent. The option is not there, then it's there. It really isn't harming anything, just sharing my findings.

> Right now the dashboard is disabled in embed by default.
I see it when I go to any project via an embed snippet.

**Comment by AdamZaczek** [comment]
Just to clarify, this issue is about avatar not being there sometimes?

**Comment by MateuszOlek** [comment]
We have fixed the "dashboard" link in the header. It will work consistently now. It will not appear in the embedded version as intended.
