### ISSUE TITLE
Loading a project hangs on loading when another is active

### ISSUE THREAD

**Issue by moT01** [stroveio/strove.io#365]
When I have a project active: 
<img width="292" alt="Screen Shot 2020-04-14 at 10 22 42 AM" src="https://user-images.githubusercontent.com/20648924/79242505-0aa4d900-7e3a-11ea-90a4-ae38cbc56b49.png">

And try to open another project via an embed snippet, it gets stuck on the "loading..."
<img width="312" alt="Screen Shot 2020-04-09 at 7 24 38 AM" src="https://user-images.githubusercontent.com/20648924/79242738-4f307480-7e3a-11ea-96e0-dcc6ee365d10.png">

To avoid this, users need to manually go to their dashboard and stop the active project before trying to load the new or other project. When you are on your dashboard and try to load a new project, you get a warning to stop the active project. 

Seems like a good UX might be to automatically stop the active project when trying to open a new one. It doesn't seem like any code would be lost by automatically stopping it for them.

**Comment by AdamZaczek** [comment]
I like it. The current behavior was intended but this will feel much smoother. Adding this to todo, thanks!

**Comment by MateuszOlek** [comment]
We applied your suggestion and the flow feels a lot better, thanks!
