### ISSUE TITLE
Stuck on loading when opening while logged out

### ISSUE THREAD

**Issue by moT01** [stroveio/strove.io#366]
**While logged out:**

When I open a project via an embedded link. I get taken to this page...
<img width="360" alt="Screen Shot 2020-04-14 at 10 57 12 AM" src="https://user-images.githubusercontent.com/20648924/79246720-31194300-7e3f-11ea-8a50-e1c5a585409a.png">
Clicking that takes me to this page in a new tab...
<img width="359" alt="Screen Shot 2020-04-14 at 10 56 43 AM" src="https://user-images.githubusercontent.com/20648924/79246751-38d8e780-7e3f-11ea-9adc-febf5d6af886.png">
Click that to log in with github and I get stuck on this loading screen...
<img width="336" alt="Screen Shot 2020-04-14 at 10 53 17 AM" src="https://user-images.githubusercontent.com/20648924/79246815-4ee6a800-7e3f-11ea-9dfa-89bd6271f01f.png">

This happens whether I am already logged in to github or not.

I'm not sure what the problem is here and I'm not sure how often people would run into it. Perhaps it's because I already have a strove account?

Only tested on:
High Sierra 10.13.6
Firefox 75.0

On few a side notes, I've only used github with strove but there's no gitlab option on this page (second picture) for those who might use that. Also, the two pages from the first two pictures feel redundant. Perhaps that's just how it is, I don't mind it much - just pointing it out. Maybe these should be separate issues.

**Comment by AdamZaczek** [comment]
I was able to reproduce, this login issue happens very inconsistently, seems like a race condition with component reload and local storage read time.

It makes sense that it occurred after you logged in for the first time, the app will take slightly more time to load as it has more local storage data to react to.

It's a pretty serious blocker, we'll take care of it asap, thanks!

**Comment by AdamZaczek** [comment]
@moT01 I made a quick, ugly fix for the issue with login. I'm not closing the issue yet as I plan to make a 100% reliable fix by the end of the week. If you have any more issues let me know!

**Comment by AdamZaczek** [comment]
#368 fixes that for good, thanks for reporting this @moT01 !

Side note: 2 login pages are actually needed - Oauth spec prevents login from within iframe with another domain.
1st login page informs user that he will visit Strove just to complete login. Once user is logged in, strove redirects back to the origin domain.
